DISPLAY_NAME = "Revvity Matrix"
DEVICE_TYPE = "cell counter"
EPOCH_STR = "1970-01-01 00:00:00"

MILLION_CONVERSION = 1000000
LIVE_CELLS_DENSITY_COL = "Live Cells/mL"
MILLION_SCALE_COLS = ["Total Cells/mL", LIVE_CELLS_DENSITY_COL, "Dead Cells/mL"]
