DISPLAY_NAME = "Beckman Echo Cherry Pick"
DEVICE_TYPE = "liquid handler"
PRODUCT_MANUFACTURER = "Beckman Coulter"
SOFTWARE_NAME = "Labcyte Echo Cherry Pick"

TRANSFER_RESULTS_LABEL = "DETAILS"
TRANSFER_ERRORS_LABEL = "EXCEPTIONS"

CHERRY_PICK_REPORT_VOLUME_UNITS = "nL"
CHERRY_PICK_REPORT_VOLUME_CONVERSION_TO_UL = 0.001
