#!/bin/sh
regex="^(docs|style|refactor|perf|test|chore):.*"
if [[ "$PR_TITLE" =~ $regex ]]; then
    exit 0
fi
git fetch origin --quiet
if [ $(git diff-tree -r --name-only --no-commit-id origin/main HEAD | grep -c CHANGELOG.md) -eq 0 ]
then
    echo "Must update CHANGELOG.md when PR title prefix is feat or fix, see CONTRIBUTING for details.
    exit 1
fi
exit 0
