#!/bin/bash
if [[ "$PR_TITLE" =~ ^(feat|fix|refactor|deprecate|remove|security|release|docs|perf|test|chore):.* ]]; then
    exit 0
fi
echo "PR title must start with one of feat|fix|refactor|deprecate|remove|security|release|docs|perf|test|chore see CONTRIBUTING for details."
exit 1
