#!/bin/sh
if [[ "${SKIP_PRE_PUSH_CHECKS:-}" == "1" ]]
then
  exit 0
fi
echo "Running lint..."
hatch run lint:style
if [ $? -ne 0 ]
then
  exit 1
fi
echo "Running mypy..."
hatch run lint:typing
if [ $? -ne 0 ]
then
  exit 1
fi

exit 0
