#!/usr/bin/env bash
set -eo pipefail

python_version=$(grep -G "^3" .python-version)
venv_name=$(grep -G "^[^3]" .python-version)

if python --version 2>/dev/null | grep -q $python_version; then
    echo "Python already installed"
else
    echo "Installing Python..."
    PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install --skip-existing "$python_version"
fi

if [[ $VIRTUAL_ENV == *$venv_name ]]; then
    echo "Python virtualenv already activated"
else
    echo "Setting up virtualenv..."
    pyenv virtualenv "$python_version" "$venv_name"
fi

# Install python packages
pip install pip-tools
# Install editable package locally
pip install -e .
