name: re-approve

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  reapprove:
    name: Reapprove
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        with:
          FILES: CHANGELOG.md
      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
        if: env.GIT_DIFF && github.event.review.state == 'approved'
